

plaintext = b'Never Gonna Give You Up'
ikm_base_s = b'base_test_ikm_sender'
ikm_base_r = b'base_test_ikm_recipient'
info_base = b'base_case_test'
aad_base = b'base_case_aad'
ikm_psk_s = b'psk_test_ikm_sender'
ikm_psk_r = b'psk_test_ikm_recipient'
psk_psk = b'preshared_key_psk'
psk_id_psk = b'0'
info_psk = b'psk_case_test'
aad_psk = b'psk_case_aad'
ikm_auth_s = b'auth_test_ikm_sender'
ikm_auth_r = b'auth_test_ikm_recipient'
info_auth = b'auth_case_test'
aad_auth = b'auth_case_aad'
ikm_auth_psk_s = b'auth_psk_test_ikm_sender'
ikm_auth_psk_r = b'auth_psk_test_ikm_recipient'
psk_auth_psk = b'preshared_key_auth_psk'
psk_id_auth_psk = b'1'
info_auth_psk = b'auth_psk_case_test'
aad_auth_psk = b'auth_psk_case_aad'
